# Generated by Django 6.0.5 on 2026-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0004_auto_create_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
